### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by liaeh** [liafacom/faquad#28]
Hi! Great work on the dataset. Under what license is it available? On the [HuggingFace datasets ](https://huggingface.co/datasets/eraldoluis/faquad) webpage, cc-by-4.0 is mentioned, but I cannot find any confirmation in this repo.

**Comment by eraldoluis** [comment]
Hi liaeh! Thank you for the interest. We didn't discuss anything about license when we developed this work. When I added the dataset to the HF hub, I just tried to choose a very open license. So I think you can assume cc-by-4.0. And in case you need something else, just tell me. This dataset is supposed to be fully open for any use.

**Comment by liaeh** [comment]
Thanks for the answer! How about adding a copy of the cc-by-4.0 license to this repository under LICENSE.txt? This would make things consistent for people coming from HF and make it clear that it is fully open 😄

**Comment by eraldoluis** [comment]
Done! Thanks for the tip. :)
